services:
  omni-tools:
    networks:
      - expander-net
    image: iib0011/omni-tools:latest
    container_name: omni-tools
    restart: unless-stopped
    ports:
      - "8300:80"

networks:
  expander-net:
    external: true
    name: expander-net